version: '3.8'

services:
  nfc-reader:
    build: .
    container_name: nfc-reader
    volumes:
      - /run/pcscd:/run/pcscd  # Mount PCSC socket from host
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
      - LOG_LEVEL=INFO  # Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
      # - WEBHOOK_URL=http://your-home-assistant:8123/api/webhook/your-webhook-id