version: '3.8'

services:
  nfc-reader:
    build: .
    container_name: nfc-reader
    volumes:
      - /run/pcscd:/run/pcscd  # Mount PCSC socket from host
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered