version: '3.8'

services:
  nfc-reader:
    image: ghcr.io/shocklateboy92/homeassistant-usb-tagreader:main
    container_name: nfc-reader
    volumes:
      - /run/pcscd:/run/pcscd  # Mount PCSC socket from host
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
      - LOG_LEVEL=INFO  # Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
      # MQTT configuration
      - MQTT_BROKER=your-mqtt-broker
      - MQTT_USERNAME=your-username
      - MQTT_PASSWORD=your-password